"""Real, widely sold products per class, prefilled from general knowledge (no web lookups, no API calls).

Prices are APPROXIMATE typical list prices in USD and may be out of date; the UI labels them that way. Names are
used only to identify the products; the project is not affiliated with any brand, and nothing is sold.
Each entry: (brand, model, approx_price_usd, style_tags, short spec).
"""
REAL_PRODUCTS = {
    "backpack": [("JanSport", "SuperBreak Plus", 45, ["classic", "budget"], "26 L, padded laptop sleeve"),
                 ("Osprey", "Daylite Plus 20", 75, ["outdoor", "minimal"], "20 L daypack, mesh back panel"),
                 ("The North Face", "Borealis", 99, ["outdoor", "sporty"], "28 L, FlexVent suspension")],
    "sunglasses": [("Knockaround", "Premiums", 25, ["sporty", "budget"], "polarized, UV400"),
                   ("Oakley", "Holbrook", 160, ["sporty", "outdoor"], "O Matter frame"),
                   ("Ray-Ban", "Original Wayfarer RB2140", 170, ["classic", "luxe"], "acetate frame, G-15 lenses")],
    "running shoe": [("Nike", "Pegasus 41", 140, ["sporty", "classic"], "neutral daily trainer"),
                     ("Brooks", "Ghost 16", 140, ["sporty", "cozy"], "neutral, soft cushioning"),
                     ("HOKA", "Clifton 9", 145, ["sporty", "outdoor"], "lightweight max cushion")],
    "sandal": [("Teva", "Original Universal", 55, ["outdoor", "budget"], "adjustable straps"),
               ("Chaco", "Z/1 Classic", 105, ["outdoor", "sporty"], "LUVSEAT footbed"),
               ("Birkenstock", "Arizona", 110, ["classic", "cozy"], "cork-latex footbed, two straps")],
    "Loafer": [("Sam Edelman", "Loraine", 130, ["classic", "luxe"], "leather bit loafer"),
               ("G.H. Bass", "Larson Weejuns", 145, ["classic", "minimal"], "leather penny loafer"),
               ("Dr. Martens", "Adrian Tassel Loafer", 150, ["classic", "luxe"], "smooth leather, air-cushioned sole")],
    "sweatshirt": [("Gildan", "Heavy Blend Crewneck", 15, ["budget", "cozy"], "cotton-poly fleece"),
                   ("Carhartt", "Loose Fit Midweight Sweatshirt", 55, ["outdoor", "cozy"], "10.5 oz fleece"),
                   ("Champion", "Reverse Weave Crew", 60, ["classic", "cozy"], "heavyweight fleece")],
    "jean": [("Wrangler", "Cowboy Cut Original Fit", 45, ["classic", "budget"], "rigid denim"),
             ("Lee", "Regular Fit", 50, ["classic", "budget"], "straight leg"),
             ("Levi's", "501 Original Fit", 80, ["classic", "minimal"], "button fly, straight leg")],
    "cardigan": [("Amazon Essentials", "V-Neck Cardigan Sweater", 28, ["budget", "minimal"], "lightweight knit"),
                 ("Uniqlo", "Extra Fine Merino Cardigan", 40, ["minimal", "classic"], "washable merino wool")],
    "sock": [("Smartwool", "Hike Light Cushion Crew", 25, ["outdoor", "cozy"], "merino wool blend"),
             ("Darn Tough", "Hiker Micro Crew Midweight", 27, ["outdoor", "sporty"], "merino, lifetime guarantee"),
             ("Bombas", "Ankle Sock 4-Pack", 50, ["cozy", "sporty"], "cushioned footbed")],
    "wallet": [("Fossil", "Derrick Bifold", 45, ["classic", "budget"], "leather, RFID blocking"),
               ("Ridge", "Aluminum Wallet", 85, ["tech", "minimal"], "holds up to 12 cards"),
               ("Bellroy", "Slim Sleeve", 89, ["minimal", "luxe"], "leather card sleeve")],
    "purse": [("Baggu", "Nylon Crescent Bag", 62, ["minimal", "budget"], "recycled nylon crossbody"),
              ("Michael Kors", "Jet Set Travel Crossbody", 200, ["luxe", "classic"], "saffiano leather"),
              ("Coach", "Tabby Shoulder Bag 26", 450, ["luxe", "classic"], "refined pebble leather")],
    "digital watch": [("Casio", "F-91W", 20, ["classic", "budget"], "resin strap, alarm, stopwatch"),
                      ("Timex", "Ironman Classic 30", 50, ["sporty", "budget"], "30-lap memory, Indiglo"),
                      ("Casio", "G-Shock DW5600", 75, ["sporty", "outdoor"], "shock resistant, 200 m water resistance")],
    "coffee mug": [("YETI", "Rambler 14 oz Mug", 30, ["outdoor", "classic"], "vacuum insulated steel"),
                   ("Le Creuset", "Stoneware Mug 12 oz", 30, ["classic", "cozy"], "enameled stoneware"),
                   ("Ember", "Mug 2, 10 oz", 130, ["tech", "luxe"], "app-controlled heated mug")],
    "water bottle": [("Nalgene", "32 oz Wide Mouth", 15, ["outdoor", "budget"], "BPA-free Tritan"),
                     ("Hydro Flask", "32 oz Wide Mouth", 45, ["outdoor", "sporty"], "insulated stainless steel"),
                     ("Stanley", "Quencher H2.0 FlowState 40 oz", 45, ["cozy", "classic"], "insulated tumbler with handle")],
    "teapot": [("Bodum", "Assam Tea Press", 30, ["minimal", "classic"], "glass, 34 oz, press infuser"),
               ("ForLife", "Curve Teapot with Infuser", 35, ["minimal", "cozy"], "ceramic, 24 oz")],
    "frying pan": [("Lodge", "10.25 in Cast Iron Skillet", 25, ["classic", "budget"], "pre-seasoned cast iron"),
                   ("T-fal", "Ultimate Hard Anodized 12 in Fry Pan", 35, ["budget", "minimal"], "nonstick, oven safe"),
                   ("All-Clad", "D3 Stainless 10 in Fry Pan", 110, ["luxe", "classic"], "tri-ply stainless steel")],
    "toaster": [("Hamilton Beach", "2-Slice Toaster", 25, ["budget", "minimal"], "extra-wide slots"),
                ("Cuisinart", "CPT-122 2-Slice Toaster", 40, ["classic", "budget"], "compact, 6 shade settings"),
                ("Breville", "Die-Cast 2-Slice Smart Toaster", 180, ["luxe", "tech"], "motorized lift-and-look")],
    "espresso maker": [("De'Longhi", "Stilosa EC260", 110, ["budget", "classic"], "manual pump espresso, steam wand"),
                       ("Nespresso", "VertuoPlus", 170, ["tech", "minimal"], "capsule coffee and espresso"),
                       ("Breville", "Bambino Plus", 500, ["luxe", "tech"], "automatic milk frothing")],
    "laptop": [("Acer", "Aspire 5", 550, ["budget", "tech"], "15.6 in, everyday laptop"),
               ("Dell", "XPS 13", 1000, ["tech", "minimal"], "13.4 in ultraportable"),
               ("Apple", "MacBook Air 13 in (M3)", 1100, ["tech", "luxe"], "fanless, all-day battery")],
    "computer keyboard": [("Logitech", "K380 Multi-Device", 40, ["budget", "minimal"], "Bluetooth, 3 devices"),
                          ("Keychron", "K2", 80, ["tech", "classic"], "75% wireless mechanical"),
                          ("Logitech", "MX Keys S", 110, ["tech", "minimal"], "backlit, multi-device")],
    "mouse": [("Logitech", "M185", 15, ["budget", "minimal"], "wireless, compact"),
              ("Razer", "DeathAdder V3", 70, ["sporty", "tech"], "ergonomic gaming mouse"),
              ("Logitech", "MX Master 3S", 100, ["tech", "luxe"], "quiet clicks, MagSpeed wheel")],
    "cellular telephone": [("Google", "Pixel 8a", 500, ["tech", "budget"], "6.1 in, Tensor G3"),
                           ("Apple", "iPhone 15", 700, ["tech", "classic"], "6.1 in, USB-C"),
                           ("Samsung", "Galaxy S24", 800, ["tech", "luxe"], "6.2 in, AMOLED")],
    "iPod": [("Apple", "iPod touch (7th gen, discontinued)", 200, ["tech", "classic"], "launch price; now sold used"),
             ("Sony", "Walkman NW-A306", 350, ["tech", "luxe"], "hi-res audio player")],
    "binoculars": [("Nikon", "Aculon A211 10x50", 110, ["outdoor", "budget"], "Porro prism"),
                   ("Bushnell", "H2O 10x42", 100, ["outdoor", "sporty"], "waterproof roof prism"),
                   ("Vortex", "Diamondback HD 10x42", 250, ["outdoor", "luxe"], "HD glass, lifetime warranty")],
    "acoustic guitar": [("Fender", "CD-60S", 200, ["classic", "budget"], "solid spruce top dreadnought"),
                        ("Yamaha", "FG800", 220, ["classic", "budget"], "solid spruce top"),
                        ("Taylor", "GS Mini", 600, ["luxe", "classic"], "compact scale, solid top")],
    "electric guitar": [("Squier", "Classic Vibe '50s Stratocaster", 450, ["classic", "budget"], "alnico pickups"),
                        ("Epiphone", "Les Paul Standard '50s", 650, ["classic", "luxe"], "mahogany body"),
                        ("Fender", "Player Stratocaster", 850, ["classic", "luxe"], "alder body, 3 single coils")],
    "umbrella": [("Totes", "AutoOpen Compact Umbrella", 25, ["budget", "minimal"], "auto-open, compact"),
                 ("Repel", "Windproof Travel Umbrella", 25, ["budget", "sporty"], "Teflon coating, 9 ribs"),
                 ("Blunt", "Metro", 80, ["luxe", "minimal"], "storm-rated compact")],
    "sleeping bag": [("Coleman", "Brazos 20°F", 40, ["outdoor", "budget"], "synthetic, rectangular"),
                     ("Kelty", "Cosmic 20", 180, ["outdoor", "classic"], "550-fill down"),
                     ("REI Co-op", "Magma 15", 380, ["outdoor", "luxe"], "850-fill down, ultralight")],
    "lipstick": [("Maybelline", "SuperStay Matte Ink", 11, ["budget", "classic"], "long-wear liquid lipstick"),
                 ("MAC", "Matte Lipstick", 25, ["classic", "luxe"], "iconic matte finish"),
                 ("Charlotte Tilbury", "Matte Revolution", 35, ["luxe", "classic"], "hydrating matte")],
    "perfume": [("Glossier", "You Eau de Parfum 50 ml", 78, ["minimal", "cozy"], "musky, skin-like scent"),
                ("Dior", "Sauvage Eau de Toilette 100 ml", 120, ["luxe", "classic"], "fresh, spicy"),
                ("Chanel", "N°5 Eau de Parfum 100 ml", 175, ["luxe", "classic"], "floral aldehyde")],
}
